# Generated by Django 4.2.16 on 2025-01-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='target',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pot',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
